language: node_js
node_js:
  - "node"

dist: trusty
  
branches:
  only:
    - master
    - /\d+\.\d+\.x/

cache:
  directories:
    - $HOME/.npm
    - node_modules

env:
  - TEST_SUITE=lint
  - TEST_SUITE=test-unit
  - TEST_SUITE=test-security

addons:
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8

before_install:
  - npm i -g npm@6.0.1
  - npm --version

install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - npm i

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - npm run $TEST_SUITE
#  - yarn run build
#  We need to pre-package a Brave build for this
#  - yarn run test-e2e



